---
- name: Check ROS and Upgrade if Needed
  hosts: lab_mikrotiks
  gather_facts: false
#  strategy: free
  vars:
   ansible_command_timeout: 120

     tasks:
       - name: Set Channel
         routeros_command:
           commands:
              - / system package update set channel=stable
       - name: Check version - populates the fields
         routeros_command:
           commands:
              - /system package update check-for-updates
       - name: Check if an update is needed
         routeros_command:
           commands:
             - "[:put ([/system package update check-for-updates])]"
         register: output
       - name: print variable
         debug:
           msg: "{{ output }}"
       - name: Run upgrade if new version is available
         routeros_command:
           commands:
              - /system package update install ignore-missing=yes
         when: output.stdout is search('available')
#       - name: System Reboot
#         routeros_command:
#           commands:
#              - :execute {/system package downgrade;}
